### ISSUE TITLE
JSON encoder does not recognize datetime object

### ISSUE THREAD

**Issue by hathschi** [ThomasAitken/Scrapy-Testmaster#5]
When passing data from the start_request() in datetime format within the meta variable of the scrapy.http.Request(), like
```
def start_requests(self):
    ...
    yield Request(url,... ,meta={...,"some_key":some_datetime_datetime_object} )
```

we receive the following error message:
```
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/twisted/internet/defer.py", line 662, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 121, in process_callback_output
    return MutableChain(process_spider_output(result), recovered)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 103, in process_spider_output
    result = method(response=response, result=result, spider=spider)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/scrapy_testmaster/middleware.py", line 201, in process_spider_output
    write_json(test_dir, _request, data['result'], index)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/scrapy_testmaster/utils_novel.py", line 238, in write_json
    json.dump(extant_fixtures, f)
  File "/usr/local/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/local/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

This error occurs only when creating fixtures with `TESTMASTER_ENABLED=True` while normal crawls run without error.
Workaround: We convert the datetime object to string but this reduces the readability of the code. And it is laborious to debug, as the test fails although the code itself is working.

**Comment by ThomasAitken** [comment]
This should be resolved with the latest version
