### ISSUE TITLE
Error of failing test is not verbose

### ISSUE THREAD

**Issue by hathschi** [ThomasAitken/Scrapy-Testmaster#6]
When running tests with `scrapy run python -m unittest`
after adding a dictionary item to be returned from the parse,
we get the following error message:

```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/testmaster/tests/github_language_tags/all_languages/parse/test_fixtures.py", line 22, in test__github_language_tags__all_languages__parse
    test(self)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/scrapy_testmaster/utils.py", line 473, in test
    six.raise_from(
  File "<string>", line 3, in raise_from
AssertionError: Callback output #0 doesn't match recorded output:


----------------------------------------------------------------------
```

The error is expected, as - of course - the new item is not contained in the fixture.
The issue here is, we expected (empty) and the actual (new) items to be displayed after `... doesn't match recorded output:` but get empty output instead.
If we did not know the source of the error by ourselves, the message would not have told how to find it.

**Comment by ThomasAitken** [comment]
The log that is usually generated showing the differences between the fixture and the test version is just the printing-out of the datadiff exception. I am not planning to change this behaviour. I'm not sure why it didn't work in this case...
